version: 2

project_name: trakt-sync

before:
  hooks:
    - "go mod download"

builds:
  - env:
      - CGO_ENABLED=0
      - BUILDER=GoReleaser
    goos:
      - linux
    ldflags:
      - -X "github.com/mfederowicz/trakt-sync/cli.date={{ .Date }}"
      - -X "github.com/mfederowicz/trakt-sync/cli.builtBy=GoReleaser"
      - -X "github.com/mfederowicz/trakt-sync/cli.version={{ .Version }}"
      - -X "github.com/mfederowicz/trakt-sync/cli.commit={{ .FullCommit }}"

archives:
  - id: trakt-sync
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
