// Package str used for structs
package str

// Options represents a app opions.
type Options struct {
	Action            string
	Items             string
	Comment           string
	CommentID         int
	CommentType       string
	CommentsSort      string
	CountSpecials     string
	Country           string
	Days              int
	Delete            bool
	Deny              bool
	Description       string
	Episode           int
	EpisodeAbs        int
	EpisodeCode       string
	ExtendedInfo      string
	FullHour          bool
	FollowerRequest   int
	Format            string
	Headers           map[string]any
	Hidden            string
	Hide              bool
	ID                string
	IgnoreCollected   string
	IgnoreWatchlisted string
	IncludeReplies    string
	InternalID        string
	Item              string
	Language          string
	List              string
	ListItemID        int
	Module            string
	Msg               string
	Notes             string
	Output            string
	PagesLimit        int
	PerPage           int
	Period            string
	Privacy           string
	Progress          float64
	Query             string
	Remove            bool
	Reply             string
	ResetAt           string
	Rating            SliceInt
	SearchField       Slice
	SearchIDType      string
	SearchType        Slice
	Season            int
	Sort              string
	SortBy            string
	SortHow           string
	Specials          string
	Spoiler           bool
	StartDate         string
	EndDate           string
	Time              string
	Token             Token
	TraktID           int
	PlaybackID        int
	Translations      Slice
	Type              string
	Timezone          string
	UserName          string
	UserSettings      UserSettings
	Verbose           bool
	Version           bool
}
