// Package consts used to store action keys
package consts

import (
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

// usage strings
const (
	ActionTypeAll        = "all"
	AddToCollection      = "add_to_collection"
	AddToHistory         = "add_to_history"
	AddToRatings         = "add_to_ratings"
	AddToWatchlist       = "add_to_watchlist"
	Aliases              = "aliases"
	AllDvd               = "all-dvd"
	AllFinales           = "all-finales"
	AllMovies            = "all-movies"
	AllNewShows          = "all-new-shows"
	AllSeasonPremieres   = "all-season-premieres"
	AllShows             = "all-shows"
	Anticipated          = "anticipated"
	Boxoffice            = "boxoffice"
	Calendars            = "calendars"
	Certifications       = "certifications"
	Checkin              = "checkin"
	Collected            = "collected"
	Collection           = "collection"
	CollectionProgress   = "collection_progress"
	Comment              = "comment"
	Comments             = "comments"
	Countries            = "countries"
	Dvd                  = "dvd"
	Episode              = "episode"
	Episodes             = "episodes"
	Favorited            = "favorited"
	Finales              = "finales"
	Genres               = "genres"
	GetCollection        = "get_collection"
	GetHistory           = "get_history"
	GetRatings           = "get_ratings"
	GetWatched           = "get_watched"
	GetWatchlist         = "get_watchlist"
	History              = "history"
	IDLookup             = "id-lookup"
	ImdbFormat           = "imdb"
	ImdbIDFormat         = "Imdb"
	Item                 = "item"
	Items                = "items"
	Languages            = "languages"
	LastActivities       = "last_activities"
	LastEpisode          = "last_episode"
	Likes                = "likes"
	List                 = "list"
	Lists                = "lists"
	Lookup               = "lookup"
	Movie                = "movie"
	Movies               = "movies"
	MyDvd                = "my-dvd"
	MyFinales            = "my-finales"
	MyMovies             = "my-movies"
	MyNewShows           = "my-new-shows"
	MySeasonPremieres    = "my-season-premieres"
	MyShows              = "my-shows"
	Networks             = "networks"
	NewShows             = "new_shows"
	NextEpisode          = "next_episode"
	Notes                = "notes"
	People               = "people"
	Playback             = "playback"
	Played               = "played"
	Popular              = "popular"
	Query                = "query"
	Ratings              = "ratings"
	Recommendations      = "recommendations"
	Related              = "related"
	Releases             = "releases"
	RemoveFromCollection = "remove_from_collection"
	RemoveFromHistory    = "remove_from_history"
	RemoveFromRatings    = "remove_from_ratings"
	RemoveFromWatchlist  = "remove_from_watchlist"
	ReorderWatchlist     = "reorder_watchlist"
	Replies              = "replies"
	SavedFilters         = "saved_filters"
	Scrobble             = "scrobble"
	Search               = "search"
	Season               = "season"
	SeasonPremieres      = "season_premieres"
	Seasons              = "seasons"
	Settings             = "settings"
	Show                 = "show"
	ShowEpisode          = "show_episode"
	Shows                = "shows"
	Stats                = "stats"
	Studios              = "studios"
	Summary              = "summary"
	Sync                 = "sync"
	TextQuery            = "text-query"
	TmdbFormat           = "tmdb"
	TmdbIDFormat         = "Tmdb"
	Translations         = "translations"
	Trending             = "trending"
	TvdbFormat           = "tvdb"
	TvdbIDFormat         = "Tvdb"
	UpdatedIDs           = "updated_ids"
	UpdateWatchlist      = "update_watchlist"
	Updates              = "updates"
	Users                = "users"
	Videos               = "videos"
	Watched              = "watched"
	WatchedProgress      = "watched_progress"
	Watching             = "watching"
	Watchlist            = "watchlist"
)

// Fupper helper function to convert string in title format
func Fupper(in string) string {
	caser := cases.Title(language.English)
	return caser.String(in)
}
