// Package consts used to store action keys
package consts

import (
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

// usage strings
const (
	ActionTypeAll      = "all"
	Aliases            = "aliases"
	AllDvd             = "all-dvd"
	AllFinales         = "all-finales"
	AllMovies          = "all-movies"
	AllNewShows        = "all-new-shows"
	AllSeasonPremieres = "all-season-premieres"
	AllShows           = "all-shows"
	Anticipated        = "anticipated"
	Boxoffice          = "boxoffice"
	Calendars          = "calendars"
	Certifications     = "certifications"
	Checkin            = "checkin"
	Collected          = "collected"
	Collection         = "collection"
	CollectionProgress = "collection_progress"
	Comment            = "comment"
	Comments           = "comments"
	Countries          = "countries"
	Dvd                = "dvd"
	Episode            = "episode"
	Favorited          = "favorited"
	Finales            = "finales"
	Episodes           = "episodes"
	Genres             = "genres"
	History            = "history"
	IDLookup           = "id-lookup"
	ImdbFormat         = "imdb"
	ImdbIDFormat       = "Imdb"
	Item               = "item"
	Items              = "items"
	Languages          = "languages"
	LastEpisode        = "last_episode"
	Likes              = "likes"
	List               = "list"
	Lists              = "lists"
	Lookup             = "lookup"
	Movie              = "movie"
	Movies             = "movies"
	MyDvd              = "my-dvd"
	MyFinales          = "my-finales"
	MyMovies           = "my-movies"
	MyNewShows         = "my-new-shows"
	MySeasonPremieres  = "my-season-premieres"
	MyShows            = "my-shows"
	LastActivities     = "last_activities"
	Networks           = "networks"
	NewShows           = "new_shows"
	NextEpisode        = "next_episode"
	Notes              = "notes"
	People             = "people"
	Played             = "played"
	Playback           = "playback"
	Popular            = "popular"
	Query              = "query"
	Ratings            = "ratings"
	Recommendations    = "recommendations"
	Related            = "related"
	Releases           = "releases"
	Replies            = "replies"
	SavedFilters       = "saved_filters"
	Scrobble           = "scrobble"
	Search             = "search"
	SeasonPremieres    = "season_premieres"
	Settings           = "settings"
	ShowEpisode        = "show_episode"
	Shows              = "shows"
	Season             = "season"
	Seasons            = "seasons"
	Stats              = "stats"
	Studios            = "studios"
	Summary            = "summary"
	Sync               = "sync"
	TextQuery          = "text-query"
	TmdbFormat         = "tmdb"
	TmdbIDFormat       = "Tmdb"
	Translations       = "translations"
	Trending           = "trending"
	TvdbFormat         = "tvdb"
	TvdbIDFormat       = "Tvdb"
	UpdatedIDs         = "updated_ids"
	Updates            = "updates"
	Users              = "users"
	Videos             = "videos"
	Watched            = "watched"
	WatchedProgress    = "watched_progress"
	Watching           = "watching"
	Watchlist          = "watchlist"
)

// Fupper helper function to convert string in title format
func Fupper(in string) string {
	caser := cases.Title(language.English)
	return caser.String(in)
}
