name: Test
on: [push] 

jobs:
  tests-on-unix:
    name: Tests on Unix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - oldstable
          - stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: go test -race -shuffle=on ./...
  
